### ISSUE TITLE
Change Swiping Direction

### ISSUE THREAD

**Issue by natalyayyad** [esthor/react-native-swipeable-list#11]
Is there a way to change the swiping direction ?

**Comment by esthor** [comment]
Hi @natalyayyad . No, not currently. Could you describe the use case you have in mind?

**Comment by esthor** [comment]
I'm closing right now because it's been a few weeks since any comments. If you have any feedback/requests about changing the swipe direction, feel free to reopen.

I've also added this to `react-native-swipeable-list` projects here: https://github.com/esthor/react-native-swipeable-list/projects/4
