### ISSUE TITLE
Does it support Expo and TypeScript?

### ISSUE THREAD

**Issue by mofengfs** [esthor/react-native-swipeable-list#13]

**Comment by esthor** [comment]
Hi. Yes, it should work with both Expo and TypeScript.

Here's a little more info:

**Expo**: `react-native-swipeable-list` doesn't rely on any native modules; it's "just javascript", so it should work just fine dropping it into any react native or expo project.

**TypeScript**:`react-native-swipeable-list` works just fine in a TypeScript project, but it currently does not have specific TypeScript exported types. What that means is you (probably) won't get any specific type safety or autocomplete hints in your code editor. I created a project for this, which you can watch for updates here: https://github.com/esthor/react-native-swipeable-list/issues/3

**Comment by esthor** [comment]
Closing now as this seems complete. Feel free to open another if there are issues running in an Expo or TypeScript project.
