### ISSUE TITLE
disable bounce

### ISSUE THREAD

**Issue by baesumin** [esthor/react-native-swipeable-list#63]
Thanks for making a great library.
Is it possible to stop scrolling beyond the required range or get rid of the bounce?

**Comment by esthor** [comment]
Glad you like the library!

Yep, if I'm understanding your wants, both of those things are possible and easy!

Set these props:

> `maxSwipeDistance` - Maximum distance to open to after a swipe. Type `number || (Object => number)`
>  `shouldBounceOnMount` (default = `true`) - To alert the user that swiping is possible, the first row can bounce on component mount. Type `boolean`

For the `maxSwipeDistance`, just set to the distance you want it to stop.

For `shouldBounceOnMount` just set it to `false` and it won't animate the initial bounce

**Comment by baesumin** [comment]
i mean, for example, even if maxSwipeDistance is set, while swiping, the swipe goes beyond the maxSwipeDistance and returns  maxSwipeDistance when i release my hand.

It would be good if it does not swipe more than maxSwipeDistance during swipe.

**Comment by esthor** [comment]
Oh, you want it to clamp at the maxSwipeDistance.

Hmm, do you have any examples of apps doing this or a use case that can help me understand? I might be so used to iOS UX patterns that this seems "unnatural" to not be able to pull/"stretch" a swipe and have it "fling" back with a sense of "inertia".

**Comment by baesumin** [comment]
yes i want it to clamp at the maxSwipeDistance. 😃

**Comment by decafdevio** [comment]
I agree, the bouncing isn't great. Items are also swipeable to the left a little. It would be great if it worked like Apple's Messages.
