### ISSUE TITLE
shouldBounceOnMount alway true

### ISSUE THREAD

**Issue by Duya3fithou** [esthor/react-native-swipeable-list#80]
shouldBounceOnMount={false}
I tried pass false value, but it alway Bounce On first Mount.
i use "react-native-swipeable-list": "^0.1.2", "react-native": "0.74.2",
Tks for pretty libs and your response

**Comment by esthor** [comment]
Oh, that's strange. I'll have a look in a bit to see if I can reproduce that. I haven't tested on 0.74.2 of react-native yet.

**Comment by esthor** [comment]
Hmm, yeah, I just tried this in 0.74 and it's not working as expected. I'll have to take a deeper look and see what's going on.

One area I'm going to look into is that it might be the use of older react native methods under the hood which may not be supported in Hermes. I'm see some hermes related warnings which may be hinting towards that. 🤔

**Comment by Duya3fithou** [comment]
Hope you can fix soon, tks you
on top of that, I think sometime we need disable swip
Can you provide that in next release?

**Comment by Duya3fithou** [comment]
I read your code, and when i pass bounceFirstRowOnMount={false} to SwipeableFlatList, like this: 
![image](https://github.com/user-attachments/assets/9864a633-8f46-4953-95f1-0bf6a755daa6)
It's work perfect what i want.

**Comment by esthor** [comment]
Oh yeah, nice find! I bet something is getting messed up in the constructor:
``` constructor(props, context) {
        super(props, context);
        this.state = {
            openRowKey: null,
        };

        this._shouldBounceFirstRowOnMount = this.props.bounceFirstRowOnMount;
    }
```


or the renderItem logic
```        let shouldBounceOnMount = false;
        if (this._shouldBounceFirstRowOnMount) {
            this._shouldBounceFirstRowOnMount = false;
            shouldBounceOnMount = true;
        }
```

Noting to myself (or you, if you wanna take a stab at it). I'll try to find some time this week to fix this.

**Comment by esthor** [comment]
Your workaround works, so I updated the example app code for now -- https://github.com/esthor/react-native-swipeable-list/pull/84

When I get some more time, I'm going to try and dig into the issue to get to the root of it. 🙏

**Comment by Duya3fithou** [comment]
> Your workaround works, so I updated the example app code for now -- #84
> 
> When I get some more time, I'm going to try and dig into the issue to get to the root of it. 🙏

Nice work!
