### ISSUE TITLE
Dynamic maxSwipeDistance

### ISSUE THREAD

**Issue by jasimchz** [esthor/react-native-swipeable-list#83]
for example if i render comment and for comment owner i need to show some extra options

**Comment by esthor** [comment]
HI @jasimchz 👋 

Could you tell me a bit more about how you'd expect this to work from your use case? That will help me understand how to provide an interface and functionality for your use case.

**Comment by jasimchz** [comment]
@esthor , Currently we need to set a fixed space for swipe 

What if i want 1st render item to show 2 items on swiper and 3 items on second item,
Also reset swipe to back on action is done

**Comment by esthor** [comment]
Oh, interesting.

If you've got some code to share, we could work off that.

Is my understanding accurate:

1. You want to show different numbers of actions, depending on the item, within the same list
2. You want the quick action items to each be the same size (let's say 100px)
3. In the case that you have 2 items, you would want that to maxSwipeDistance to be 200px, but for 3 items, it'd be 300px (assuming our 100px for each example).
4. You also want a method to be able to set the swiped row to hide the actions once an action has been taken.
