### ISSUE TITLE
shouldBounceOnMount属性设置为false之后动画效果依然存在

### ISSUE THREAD

**Issue by delicacy001** [esthor/react-native-swipeable-list#86]

**Comment by esthor** [comment]
(Google Translate): "The animation effect still exists after the shouldBounceOnMount property is set to false"


Hi @delicacy001, this is a simple workaround for your right now:
```
// shouldBounceOnMount={false} -- This is not working on 0.74+ React Native
bounceFirstRowOnMount={false} // THIS IS THE WORKAROUND

```
See the update in the example app:
https://github.com/esthor/react-native-swipeable-list/pull/84#issue-2488144256

**Comment by delicacy001** [comment]
Ok,Thank you!
