### ISSUE TITLE
New Architecture for Expo 52

### ISSUE THREAD

**Issue by mister-conor** [esthor/react-native-swipeable-list#88]
This is showing as "Untested on New Architecture" when building on EAS servers. Will this be updated to support the new architecture? Thanks

**Comment by esthor** [comment]
I will have to test this out soon. I don't currently use EAS. Is there anything else the logs say? Does this cause a build failure or just a warning?

**Comment by mister-conor** [comment]
Cheers. It is a warning in the build step that runs expo doctor on EAS. It can also be seen by running `npx expo-doctor` locally.

![image](https://github.com/user-attachments/assets/0cc505f5-1bc7-4170-a2dc-7275305cb5d1)

It does not cause the build to fail and the package seems to function as expected from what I've seen on both Android and iOS devices. I have not opted in to using the new architecture in my project yet however as I am making sure upgrading to Expo 52 works as expected first as per advice in the Expo 52 [changelog](https://expo.dev/changelog/2024/11-12-sdk-52) so I will need to test on the new architecture also.

**Comment by esthor** [comment]
I just tested in a fresh React Native 0.76.3 install and looks good.

I think once [this React Native Directory PR](https://github.com/react-native-community/directory/pull/1403/files) gets merged, you won't see this warning anymore when building on EAS servers or `expo-doctor` directly.

I believe the only thing needed is the `"newArchitecture": true` value in that directory listing. 🙏

**Comment by mister-conor** [comment]
Thank you for this. I will test again once the PR is merged and revert.

**EDIT:** The warning is now gone, thanks.

**Comment by esthor** [comment]
Woo! Thanks for being so quick to test it @mister-conor! 🎉
