### ISSUE TITLE
Close the swipeable

### ISSUE THREAD

**Issue by BogdanRad** [esthor/react-native-swipeable-list#9]
how can to close the swipeable after pressed the option?

![image](https://user-images.githubusercontent.com/40359109/94557269-02fdb300-0267-11eb-9380-8b2a74e7b83a.png)

**Comment by BogdanRad** [comment]
@esthor can you help me?

**Comment by BogdanRad** [comment]
I want to close the swipeable when i press on mute button
![image](https://user-images.githubusercontent.com/40359109/94558805-0134ef00-0269-11eb-87a8-1cfdd804cb1b.png)

**Comment by esthor** [comment]
the simplest would be to create a function that changes your list of items. So when `delete` is pressed, it calls a function that updates the list to no longer include that item.

**Comment by esthor** [comment]
You could also use the `onClose()` method...but I think in the real world a "delete" or a "mute" shouldn't just be a frontend concern. You probably want to update that data at the source, so when someone reloads the app or accesses on another device, they are having the same experience. Does that answer your issue?

**Comment by esthor** [comment]
I also just updated the example app with some functionality on the quick actions. You might want to check it out: https://github.com/esthor/react-native-swipeable-list/blob/3541412a0186a4da464c14f772bf3dc248519dbe/examples/SwipeableFlatListExample/App.js#L64-L69

**Comment by BogdanRad** [comment]
Thank you @esthor

**Comment by jasenkabalac** [comment]
I am having the same problem with closing the list. My data don't change after pressing the option, so I can't update the list. I am just navigating to another screen and when I return it is still open. Please help!

**Comment by esthor** [comment]
Hi @jasenkabalac It sounds like all you need to do is call a function in the onPress of your Quick Action item, like instead of just navigation, the onPress function would update data & navigate? It would be easier to help if we could see your code. Could you post a link to a codesandbox or post a snippet here?

**Comment by esthor** [comment]
I'm closing this issue. Please feel free to comment with more details or start a new issue if problems persist.

**Comment by Cardistymo** [comment]
very sorry for reopening this, but I just spent too much time on this.
 if you have the same problem: dont just pass the item index as key in "keyExtractor", otherwise the next item is open after you delete one item! just real unique ids!
